# @Author: nxtonic
# @Date:   2016-05-17T19:41:32+10:00
# @Last modified by:   nxtonic
# @Last modified time: 2016-05-17T19:46:20+10:00

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ~/nxtonic
email: nxtonic@gmail.com
description: > #
  The personal website of Angus McMillan
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nxtonic.github.io" # the base hostname & protocol for your site
logo: "/static/img/logotype.svg"
twitter:
  username: nxtonic
github:
  username: nxtonic

# Build settings
timezone: Australia/Melbourne
permalink: "/blog/:year/:month/:categories/:title/"
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
markdown: kramdown
highlighter: rouge
feed:
  path: atom.xml
kramdown:
  input: GFM

# Front matter defaults
collections:
  work:
    output: true
defaults:
  -
    scope:
      path: ""
    values:
      author: "Angus McMillan"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: "_work"
      type: "work"
    values:
      categories: work
      layout: work
